### ISSUE TITLE
Catch sync or async exceptions

### ISSUE THREAD

**Issue by brandon-leapyear** [fpco/unliftio#79]
It would be great if `UnliftIO.Exception` could define
```
-- Same as catch, except only catches async, rethrowing sync
catchAsync = ...

-- Explicitly catches sync and async exceptions
catchSyncOrAsync = Unsafe.catch
```
along with similar functions for `handle` and `try`. I have some code that should handle async exceptions as well, but I'd like to avoid lifting my overall ban on `Control.Exception`, even for a single module.

Thoughts?

**Comment by snoyberg** [comment]
This came up with @kazu-yamamoto recently as well. I'm not sure what the advantage of `catchAsync` would be, since that's the behavior of `catch` and related functions already. But I'd be OK with a `catchSyncOrAsync`. It would be nice to have a simpler name, but that's at least explicit.

I'd be up for a PR adding this if you're interested.

**Comment by brandon-leapyear** [comment]
catchAsync is slightly different than the others, the key part being that
it ignores sync exceptions and only catches async exceptions (just like how
unliftio's catch ignores async exceptions and only catches sync exceptions).

I mostly included catchAsync for completion; I'm thinking it could be
helpful to rename catch to catchSync (e.g. catchSyncJust, catchSyncAny) and
have similar analogues for catchAsync and catchSyncOrAsync. But it probably
won't be as helpful as I think it might be.

I'm willing to put up a PR! What do you think should go in? I'm thinking
just catchSyncOrAsync, handleSyncOrAsync, and trySyncOrAsync? Verbosity is
fine, I think, because trying to handle async exceptions is not a route we
should make easy for people to use.

**Comment by snoyberg** [comment]
I didn't pick up on what you were saying about `catchAsync`. I'd definitely omit that one, I don't see an advantage to including it, and lots of _disadvantage_ (leading people in the wrong direction).

I'd rather leave `catch` named as-is right now. Not just because breaking changes are bad. I don't want to add cognitive overhead to choosing what is in the vast majority of the cases the right function.

> I'm thinking just catchSyncOrAsync, handleSyncOrAsync, and trySyncOrAsync

Sounds perfect. Please include some documentation explaining how they behave differently than `catch`/`handle`/`try` and when you may or may not want to use them. Thank you!

**Comment by kazu-yamamoto** [comment]
For me, adding the following sentence is good enough:

> If you want to catch asynchronous exceptions, you should use `Control.Exception.catch`.

**Comment by brandonchinn178** [comment]
I'm trying to write a test, but I can't even get it working with `Control.Exception`.
```hs
result <- do
  a <- async $ EUnsafe.try $ do
    threadDelay (5 * 1000000)
    throwIO Exception2
  threadDelay (1 * 1000000)
  throwTo (asyncThreadId a) Exception1
  wait a
result `shouldBe` (Left Exception1 :: Either Exception1 ())
```
```
uncaught exception: SomeAsyncException
Exception1
```
I would think that `Control.Exception`'s `try` would catch the async `Exception1`, and `wait a` would return `Left Exception1`. Is this right?

**Comment by snoyberg** [comment]
That example works for me:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-17.12 script
import Test.Hspec
import Control.Exception as EUnsafe
import Data.Typeable
import Control.Concurrent
import Control.Concurrent.Async

data Exception1 = Exception1
  deriving (Show, Typeable, Eq)
instance Exception Exception1
data Exception2 = Exception2
  deriving (Show, Typeable, Eq)
instance Exception Exception2

main :: IO ()
main = hspec $ do
    it "foo" $ do
        a <- async $ EUnsafe.try $ do
            threadDelay (5 * 1000000)
            throwIO Exception2
        threadDelay (1 * 1000000)
        throwTo (asyncThreadId a) Exception1
        result <- wait a
        result `shouldBe` (Left Exception1 :: Either Exception1 ())
```

**Comment by brandonchinn178** [comment]
hm what if you use unliftio's throwTo?

**Comment by snoyberg** [comment]
Then it fails like yours. That's because `throwTo` from `unliftio` is wrapping up the `Exception1` in a wrapper to force it to look like an async exception. You should provide an `Exception` instance for `Exception1` that leverages `SomeAsyncException` to avoid that, or use `EUnsafe.throwTo`.

**Comment by kazu-yamamoto** [comment]
I'm using a pair of `throwTo` and `catch` in the *same* module. :-)
